CREATE TABLE public.subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email character varying NOT NULL,
    name character varying NULL,
    CONSTRAINT subscriptions_pkey PRIMARY KEY (id, email)
) TABLESPACE pg_default;

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
